conversation = ['hola','¡Hola!, en que puedo ayudarte',
    'hola como estas','¡Hola!, bien gracias y tu',
    'bien','Que bueno, en que puedo ayudarte',
    'bien gracias','Que bueno, en que puedo ayudarte',
    'adios', '¡Hasta luego! Siempre estaré aquí para ayudarte',
    'adios, nos vemos', '¡Hasta luego! Siempre estaré aquí para ayudarte'
    'adios, hasta luego', '¡Hasta luego! Siempre estaré aquí para ayudarte',
    'Que es el forraje hidroponico','El forraje verde hidropónico es el resultado del proceso de germinación de granos de cereales o leguminosas (maíz, avena, cebada, trigo, alfalfa etcétera) sobre charolas. Se realiza durante un periodo de 8 a 14 días, captando la energía del sol y asimilando los minerales de la solución nutritiva.',
    'que es el humus de lombriz',
    "Humus de lombriz o lombricomposta consiste en una serie de operaciones relacionadas con la cría y producción de lombrices detritívoras (formadoras de humus) y el tratamiento, por medio de ellas (mediante procesos de oxidación biológica), de residuos biológicos orgánicos para su reciclaje en forma de abono denominado humus de lombriz, lombrihumus o lombricompost",
    'con que se puede elaborar la composta',
    '1. Se agrega materia orgánica/desechos orgánicos cada día, se llena la caja hacia una dirección y se tapa con tierra; después de una semana se introducen las lombrices.\n 2. Se sigue añadiendo materia orgánica fresca, mientras las lombrices se reproducen y comen desechos ya medio podridos. \n 3. Después de dos o tres meses se puede empezar a cosechar la tierra donde se empezó, mientras las lombrices siguen la materia orgánica y a no necesitan estar presentes en la tierra “trabajada”',
    'con que se puede elaborar la composta',
    'Se puede elaborar con diversos elementos los cuales se dividen en:\n Adecuados: Restos de verduras y frutas, Peladuras de tubérculos, Hojas secas Papel sin tinta (servilletas de papel), Posos de café, Cáscaras de huevo \n No adecuados: Carne, Pescado Alimentos, cocinados o con aceites',
    'para qué sirve el humus de lombriz',
    'Proporciona a los suelos permeabilidad tanto para el aire como para el agua. \nAumenta la retención de agua y la capacidad de almacenar y liberar nutrientes requeridos por las plantas.\n Presenta una alta carga microbiana que resulta de la actividad biológica del suelo, entre otras ventajas',
    'que se requiere para el humuz de lombriz',
    'Una caja con tabique necesita un colado en el fondo, pues el exceso de humedad se tiene que drenar durante las lluvias. También se necesitan tapas.',
    'Dosis de aplicación entre humus y quimicos',
    'Lombricomposta: a mayor cantidad, mayor beneficio.\nFertilizantes químicos: en dosis excesivas hay raves perjuicios para el suelo y el ser humano.',
    'tiempo de vencimiento del humus de lombriz',
    'El Humus de lombriz puede llegar a durar hasta 5 años',
    'como elaborar una lombricomposta',
    'en huacales o cajas de plástico, cuidando que las compostas no se sequen (colocar cartón o plástico agujerado en el fondo) y agregar materia orgánica conforme las lombrices la van procesando. Cuidado con los excesos de humedad, pero tampoco deje secar su composta, porque las ombrices dejan de reproducirse y se van. Necesitan una humedad relativa de 70% en el suelo. La temperatura ideal para que se reproduzcan es e 1 grados. No les gustan las temperaturas elevadas o los fríos excesivos. Ubicar en un rincón protegido y sombreado no demasiado lejos de la ocina. La lombricomposta terminada (en general consiste en los excrementos de las lombrices), se considera “oro” para nutrir plantas y ortalizas, es una tierra riquísima en materia orgánica, minerales y nutrientes. Los contenedores pueden ser cajas de plástico (con drenaje para el exceso de agua), de madera o bien contenedores hechos de tabiqueo cemento. Para separarlas de la tierra se les agrega alimento en sólo na esquina de la caja durante unos días, así todas se concentran ahí y la tierra puede cosecharse del resto de la caja.',
    'cual es la cantidad adecuada de materiales para la lombricomposta',
    'Para el Humus sólido en cultivos extensivos basta con 0,5 kg/m2. En huertas, la dosificación es mayor, de al menos 2 kg/m2. El Humus líquido se aplica de 20 a 30 L/Ha, aunque depende mucho del cultivo a tratar con 2 a 4 aplicaciones a lo largo de la temporada.',
    'por qué el humus de lombriz es ecologico',
    'El humus de lombriz es considerado ecológico porque se produce a partir de la descomposición de material orgánico por medio de lombrices, en lugar de utilizar productos químicos o procesos industriales. Esto hace que sea un producto natural y sostenible, ya que no utiliza ningún tipo de producto químico y contribuye a la conservación del suelo y a la biodiversidad.',
    'de donde deriva el humus de lombriz',
    'El humus de lombriz es un derivado de la lombricultura y se refiere a un producto soluble en agua y muy fino rico en nutrientes, que aplicado al suelo mejora diferentes aspectos, como el caso de la germinación y crecimiento de diferentes especies de cultivos.',
    'Cuales son los terminos para la aplicacion del humus de lombriz',
    'Es un producto de pH neutro, lo que lo hace deseable para aplicarlo a diferentes cultivos en diferentes dosis y mínimos riesgos de quemaduras',
    'humus de lombriz mejora la calidad del suelo',
    'Uno de los pilares fundamentales de cualquier cultivo, tanto en lo que respecta a plantas de huerto como a plantas en general. Usar humus de lombriz no solo permite favorecer la airea ción del suelo. Además ayuda a mejorar un suelo arcilloso, aportándole un grano más arenoso. Por último, su textura mejora también la textura del suelo. Y no repercute en positivo en la vida de las plantas. También nos permite trabajar el suelo con más facilidad y sin que oponga resistencia.',
    'como usar humus de lombriz en el cesped',
    'Tanto si estamos en plena faena de los cuidados del césped en febrero como si los hemos postergado, el humus de lombriz será un fantástico abono ecológico para esta época. También es ideal para cuando nos planteemos resembrar el césped en otoño o en primavera.',
    'como usar el humus de lombriz al trasplantar',
    'El momento de plantación de cualquier planta es uno de los más comprometidos para su salud. Habitualmente, el cambio demaceta o de lugar supone un estrés para la planta. Algo que le hace bajar la guardia y estar más expuesta a enfermedades y plagas. Algo especialmente sensible en plantas con raíz desnuda y árboles. Para ayudarles a protegerse pero, también, para promover el enraizamiento nada como usar humus de lombriz. Es recomendable hacer una pasta con agua y esta enmienda, y meter en ella las raíces antes de trasplantar.',
    'como funciona el humus de lombrisz',
    'Las lombrices se alimentan de residuos, y el resultado es un producto único, libre de semillas activas u hongos; que no puede ser superado por ninguna otra sustancia. La calidad y cantidad del humus se debe a los microorganismos que coexisten en el intestino de la lombriz. El humus se compone de flora bacteriana que trasmite nitrógeno, potasio y fósforo; también contiene ácidos fúlvicos, los cuales estimula las raíces',
    'cuales son los componentes y valores medios del del humus de lombriz',
    'Nitrógeno 1.95 – 2.2% • Fósforo 0.23 – 1.8% • Potasio 1.07 – 1.5% • Calcio 2.70 – 4.8% • Magnesio 0.3 – 0.81% • Hierro disponible 75 mg/l • Cobre 89 mg/kg • Zinc 125 mg/kg • Manganeso 455 mg/kg • Boro 57.8 mg/kg • Carbono Orgánico 22.53 % • C/N 11.55 % • Ácidos Húmicos 2.57 g cada 100g • Carga bacteriana • Materia Orgánica 38%',
    'como estimular la reproducción de las lombrices',
    'Si queremos estimular o aumentar la reproducción de nuestras lombrices podemos utilizar pequeños trucos caseros para ello. El café es un buen estimulante para las lombrices que además de aportar nutrientes a nuestra mezcla, también aporta esponjosidad.',
    'que lombrices se deben utilizar',
    'Las lombrices californianas (Eisenia Foetida) son sanitizadoras naturales, no contraen ni transmiten enfermedades, dado que se alimentan de hongos, bacterias y protozoos, flora microbiana degradadora y generadora de enfermedades.',
    'cuantas lombrices son necesarias',
    'Nuestra recomendación si no tenemos experiencia es empezar con poca lombriz, no más 200/400 lombrices',
    'el compostaje atrae ratas',
    'El compostaje no atrae ratas en tanto se respete la pauta de separación: nada de carnes, pollo ni pescado. Sólo colocaremos en la compostera los residuos orgánicos vegetales y las cáscaras de huevo que, mezclados con los residuos secos, formarán una pila que no resulta apetecible para las ratas.',
    'que hacer si aparecen moscas en mi compostera',
    'Como pauta general, las mosquitas aparecen cuando la compostera está muy húmeda las más comunes son unas pequeñitas que aparecen en el verano, llamadas “moscas de la fruta o del vinagre” (género Drosophila).Podemos fabricar una trampa casera de mosquitas con una botella plástica transparente pequeña con tapa. Le hacemos perforaciones de 3 mm en la parte superior, y colocamos vinagre de manzana en su interior (aproximadamente 2 cm)',
    'que hacer si aparecen hormigas en mi compostera',
    'Las hormigas son indicadoras de que la pila está muy seca. Esto suele suceder en composteras que apoyan directamente sobre el suelo. Para espantarlas, evitar que construyan su hormiguero y asegurar la humedad necesaria a la transformación, regaremos la pila.',
    'que pasa si no tengo lombrices de california',
    'Puedes usar Las lombrices rojas, tambien se llaman epigeas y viven en la superficie, aguantan cambios de temperatura y cambios de humedad, incluso aguantan temperaturas mas elevadas, esto es bueno cuando las tenemos en la pila de compost que generalmente levanta temperatura cuando se liberan las moleculas de nitrogeno durante la compostacion',
    'influencia biologiaca del humus de lombris',
    'Aporta microorganismos útiles al suelo. \n• Sirve a su vez de soporte y alimento de los microorganismos',
    'el humus de lombris se destruye',
    'Los aportes de biocidas, plaguicidas, y fertilizantes pueden degradar o eliminar el humus.',
    'el humus de lombris tiene mal olor',
    'Las lombrices se alimentan de residuos, y el resultado es un producto único, libre de semillas activas u hongos; que no puede ser superado por ninguna otra sustancia. La calidad y cantidad del humus se debe a los microorganismos que coexisten en el intestino de la lombriz. El humus se compone de flora bacteriana que trasmite nitrógeno, potasio y fósforo; también contiene ácidos fúlvicos, los cuales estimula las raíces',
    'el humus de lombris protege a mis cultivos?',
    'Numerosos estudios demuestran que la acción microbiana del humus contribuye al control, reducción y/o supresión de patógenos vegetales y hongos. Asi que si, si protege tus cultivos',
    'que apariencia tiene el humus de lombris',
    'Es un producto estabilizado, con un pH neutro, se encuentra natural y completamente libre de semillas, patógenos, pesticidas y metales pesados. ',
    'que contiene el Humus de Lombriz',
    'Esta formado única y exclusivamente por las excretas o turrículos, producto de la digestión natural de las lombrices composteadoras; se presenta en la forma de infinidad de agregados cilíndricos, de uno o dos milímetros de longitud, cubiertos por una fina película mucoprotéica, “membrana peritrófica” que aglutina y retiene los compuestos derivados de la transformación orgánica de los desechos: Nitrógeno mineral y de liberación lenta, Fósforo, Potasio, macro, micro nutrientes, compuestos orgánicos reguladores de los procesos de crecimiento y desarrollo de las plantas.',
    'como funciona el Humus de Lombriz',
    'Los ácidos húmicos, las enzimas, las hormonas, las vitaminas y los antibióticos, son compuestos activos que funcionan como verdaderos reguladores de los procesos bioquímicos de las plantas y los suelos; interactúan de manera repetida sin desactivarse y ademas regulan la liberación o absorción de otros nutrientes presentes en los suelos',
    'el humus de lombris sirven para cualquier tipo de cultivo',
    'Nuestros productos pueden usarse para todo tipo de cultivo. No existe riesgo de toxicidad ni posibilidad de dañar a la planta por aplicaciones excesivas.',
    'cuanto comeran mis lombrices',
    'Esto depende de cuántas lombrices usted tenga. Estos gusanos pueden comer el equivalente a mitad o la totalidad de su propio peso corporal cada día (según las condiciones de crianza) y pueden doblar a su población cada pocos meses. Si usted comienza con un kit familiar que contiene alrededor de 2.000 lombrices maduras ( son las que tienen una hinchazón en forma de anillo alrededor de su cuerpo) consumirán cerca de dos kilogramos de basura por día. Las lombrices más pequeñas no comerán mucho y tomarán cerca de 3 meses en alcanzar la madurez. En un criadero comercial hay una mayor densidad de animales lo que disminuye los rendimientos.',
    'Como puedo ayudar a los gusanos a comer mas',
    'Las lombrices se alimentarán más rápidamente una vez que se hayan adaptado a un nuevo alimento. También comerán más si la basura se corta en pedazos pequeños, se tritura o se procesa. Temperaturas de alrededor 24 grados son ideales para favorecer una máxima producción. Las lombrices tardaran en ingresar en alimentos muy ácidos tales como cebollas y cáscaras de naranja. Un puñado de cal, cáscaras de huevos molidas, conchilla, o cenizas ayudarán a balancear en poco tiempo el efecto de alimentos ácidos.',
    'que alimentos se deben evitar dar de comer a mis lombrices',
    'Tenga cuidado con alimentar a sus gusanos con productos de fuente desconocida. Los estiércoles de caballos, ganados o perros alimentados conciertos balanceados pueden contener vermicidas activos que, así como matan a los gusanos parásitos en el animal, también pueden matar a todas sus lombrices en un día. Si va a utilizar ese tipo de abonos animales, déjelo fermentar unos cuantos días y haga una prueba de supervivencia con unos pocos animales antes de aplicarlo a gran escala. No les dé: metales, goma, plásticos, productos químicos, aceites, solventes, insecticidas, jabones, pintura, etc. Evite plantas venenosas o las que se han rociado con insecticidas.',
    'que rango de temperaturas pueden soportar las lombrices',
    'Los gusanos tolerarán una gama de temperaturas ancha de cerca de 10 30 grados C (50 - 90 grados F). Si la temperatura aumenta por encima riegue la unidad y asegúrese que este a la sombra. En lugares muy fríos o donde hay riesgo de heladas las cunas comerciales se colocan bajo cubiertas. En el caso de la crianza familiar de lombrices las Composteras son cajones portátiles que cuando hace mucho frío se trasportan a lugares más cálidos, por ejemplo un sótano o el lavadero. Si las lombrices se encuentran en un balcón, cubra la unidad con una alfombra vieja o una manta para conservar la temperatura. Una alimentación más abundante producirá calor al descomponerse. El mejor lugar para tener una compostera (si se mantiene un estricto control) es en el interior de la casa donde la temperatura permanece constante.',
    'puedo alimentar a mis lombrices con material de recorte del jardin',
    'Si, siempre que se trate de cantidades manejables. Si el volumen fuera muy grande, es mejor hacer un compostado previo mediante una pila de fermentación aeróbica y luego dárselo a las lombrices poco a poco.',
    'se pueden trasladar lombrices californianas a la huerta o al jardin',
    'Si, siempre que el suelo cuente con una gruesa cubierta vegetal. El motivo es que estos animales no construyen túneles bajo tierra como las lombrices grises y por lo tanto requieren un medio húmedo superficial donde refugiarse.',
    'Cuanto debo regar y con qué frecuencia', 'La frecuencia del regado se vincula al mantenimiento de la humedad de la capa superior de los residuos a procesar. Se deben evitar los encharcamientos ya que un exceso de agua desplaza el aire del material y provoca un tipo de fermentación (llamada anaeróbica) indeseable que se pone en evidencia por presentar un olor desagradable. Cualquier material seco, como estiércol viejo, periódicos o cartón necesita ser humedecido antes de ser agregado.',
    'hasta cuanto crecera la población de lombrices?',
    'Las lombrices regularán su población a los límites del espacio disponible y de la cantidad de alimento que usted les dé.','cual es el beneficio para mi',
    'Todos estos efectos y propiedades beneficiosas se traducen en un ahorro económico, un mejor desarrollo vegetal y un mas fácil y consistente manejo en la producción en charolas de germinación',
    'qué apariencia tiene',
    'Es un producto estabilizado, con un pH neutro, se encuentra natural y completamente libre de semillas, patógenos, pesticidas y metales pesados. Tiene un olor agradable a tierra fresca, de una coloración café obscura, casi negra y con una uniformidad, ligereza y porosidad que le confieren características físicas, calidad y presentación excepcionales.',
    'beneficios del humus de lombriz',
    'Desintoxica los suelos contaminados con productos químicos e incluso metales pesados. Aumenta las defensas contra plagas y enfermedades en los cultivos. Incrementa la producción. Favorece el incremento gracias a su potente microvida. Ahorra Agua. Entre un 15 y un 25% de agua de riego, por su elevada capacidad hídrica. Equilibra la planta. Tiene un PH neutro por lo que ayuda a restaurar el equilibrio de la planta.', 'el humus se puede comercializar',
    'Para comercializar el humus de lombriz, es importante seguir algunos pasos clave: • Obtener los permisos y registros necesarios: Antes de comercializar el humus de lombriz, es importante verificar si se necesitan permisos o registros específicos para vender productos agrícolas.Definir el mercado: Antes de comercializar el humus de lombriz, es importante definir el mercado objetivo. Diseñar el empaquetado y la etiqueta: El empaque y la etiqueta deben ser atractivos y claros, y deben proporcionar información detallada sobre el contenido del producto, los ingredientes, el modo de uso y las precauciones de seguridad.',
    'como usar el humus de lombriz para plantas',
    'Uno de los usos menos habituales del humus de lombriz, pero que ha ido ganando terreno a medida que se conocen los beneficios de esta enmienda. Nuevamente y como sucede en el huerto, cómo usar humus de lombriz en plantas varía sustancialmente según sus características y lugar de plantación. • Las plantas en maceta necesitan una aplicación regular de humus de lombriz y en pequeñas cantidades. Lo ideal es aplicarlo cuatro veces al año, y empleando entre 30 y 50 gramos en cada dosis \n• Para rosales y arbustos, lo ideal es aplicar medio kilo de esta enmienda en la base y alrededores • En el caso de los árboles ornamentales, tendremos que acolchar la base del árbol y añadir entre dos y cuatro kilos al sustrato original.',
    'propiedades del humus de lombriz',
    'El humus de lombriz es considerado uno de los mejores fertilizantes orgánicos del mundo, al ser el resultado de la digestión de múltiples microorganismos y como punto final el paso por el tubo digestivo de la lombriz californiana, el cual le aporta propiedades antibióticas, potenciadores radiculares',
    'cuanto produce una bandeja de forraje hidroponico',
    'Cada bandeja recibe 1,4 kilos de semilla',
    'Cuanto rinde el maíz hidroponico',
    'La producción de granos germinados para uso forrajero bajo control de temperatura y humedad relativa, densidad, humedad y buena calidad de la semilla; alcanza un rendimiento de 10 a 12 veces el peso de la semilla, en pasto fresco y una altura de 20 cm, aproximadamente, en un periodo de 7 a 10 días.',
    'Cuantas veces al día se riega el forraje verde hidroponico',
    'Riego en 6 ó 9 veces en el transcurso del día, con una duración menor a 2 minutos. Fertilización con solución nutritiva. Al aparecer las primeras hojas, al cuarto o quinto día después de la siembra, aplicar riegos con solución nutritiva.',
    'cuanto tiempo dura un cultivo hidroponico',
    'Así, se estima un ciclo total de la lechuga hidropónica entre 38 a 47 días.',
    'hay que cambiar el agua en hidroponia',
    'Cambios completos de agua: El mejor momento para cambiar el agua hidropónica por completo es después de haberla llenado suficientes veces para llenarla por completo. Para un sistema hidropónieco de tamaño promedio, es probable que deba cambiar el agua cada dos o tres semanas.',
    'como se elabora el forraje hidroponico',
    'Selección de semilla. Emplear semilla de alta calidad, adaptada a las condiciones locales, disponibles y de probada germinación y rendimiento.\n 2.- Lavado y desinfección de semillas. Se dejan las semillas menos de 30 segundos en hipoclorito de sodio al 1% (10 ml.) por cada litro de agua; para eliminar hongos y bacterias y dejarlas limpias. \n3.- Pre-germinación. A las 12 horas de estar sumergidas, escurrirlas durante 1 hora. Sumergirlas nuevamente 12 horas. Induce la rápida germinación de la semilla.\n 4.- Siembra y densidad. Las densidades óptimas por metro cuadrado oscilan entre 2.2 a 3.4 kg de semilla. Se distribuirá una delgada capa de semillas pre-germinadas, la cual no debe ser mayor a 1.5 cm de altura o espesor.\n 5.- Germinación. Después de la siembra, las semillas se cubren con papel periódico para favorecer la germinación y el crecimiento inicial. Una vez detectada la germinación de las semillas se retira el papel.\n 6.- Riego. El riego de las bandejas de crecimiento del FVH puede realizarse a través de micro aspersores, nebulizadores o con una bomba aspersora portátil (mochila de mano). Riego en 6 ó 9 veces en el transcurso del día, con una duración menor a 2 minutos.',
    'que maiz es mejor para forraje hidroponico',
    'El maíz, con los granos en estado pastoso, es el más adecuado para usar como forraje.',
    'que semilla se usa para el forraje hidroponico',
    'Para este tipo de forraje se utiliza principalmente semillas de gramíneas, como trigo, avena, cente- no, triticale, cebada, o maíz.',
    'Que ventajas tiene el forraje verde hidroponico',
    'El Forraje Verde Hidropónico tiene numerosas ventajas, entre ellas destaca que es un alimento de fácil y rápida obtención (en 14 días ya está listo para el consumo). Además de ello necesita poco espacio para su producción y bajas cantidades de agua.',
    'Puedo alimentar animales con el forraje hidroponico',
    'Según este investigador: “El forraje verde hidropónico no solo es una alternativa de producción de forraje para el alimento animal como el ganado de leche y de carne, cabras, cerdos, gallinas, caballos y conejos',
    'Como evitar el hongo en el forraje verde hidroponico',
    'con cal, por cada 20 lts de volumen, añadir 150 grs. de cal; esto para que la cal abra la folícula y salga la raíz. Después lavar y dejar reposar en un recipiente que tenga buen drenaje por 24 hrs., y despues depositar para su siembra en el contenedor debidamente desinfectado con jabón y cloro; esto para evitar hongos.',
    'que usos se le puede dar al forraje verde hidroponico',
    'Según Laila Bernal, el forraje verde hidropónico (F.V.H) es un sistema de cultivos utilizado para producir alimentos a partir de una solución acuosa y nutritiva',
    'Que porcentaje de proteina tiene el forraje verde hidroponico',
    'El contenido de proteína cruda (PC) (13-14 %) y energía metabólica (2.4-2.5 Mcal·kg-1 MS) del FVH es suficiente para satisfacer los requerimientos de diversos tipos de ganado (Anónimo, 2001).',
    'Que forraje es mejor para el ganado',
    'Algunas opciones, como la avena y el raigrás, que se cultivan junto a la hierba de Guinea, pueden producir un buen forraje durante la época más fría del año, sirviendo incluso como alimento para las vacas lecheras entre junio y septiembre.',
    'Por que crece moho en mi sistema hidroponico',
    'Causas del moho en hidroponía: La causa más común del moho es el exceso de agua . La hidroponía, en particular, usa agua con fertilizante y empapa las raíces de las plantas para que crezcan. Por lo tanto, el agua rica en nutrientes no solo es propicia para el crecimiento de las plantas sino también para el crecimiento de microorganismos',
    'Como evitar la aparicion de algas en hidroponia',
    'Para ello, mezcla una parte de peróxido de hidrógeno por cada diez partes de agua. Luego ve mezclando frecuentemente pequeñas cantidades de esta mezcla en tu depósito de agua. Además de eliminar las algas, ¡esta mezcla aporta oxígeno a las raíces!',
    'Como combatir las plagas en hidroponia',
    'La eliminación y destrucción de plantas enfermas ayuda a controlar los problemas producidos por hongos o virus. Comprende el uso de trampas, aplicación de aceites, control de la humedad ambiental, mallas contra insectos, etc.',
    'Como desinfectar sustratos hidroponicos',
    'Los dos principales agentes de desinfección química que se pueden utilizar para tratar los suministros de agua y las soluciones de nutrientes hidropónicos son el peróxido de hidrógeno (H2O2) y el cloro.',
    'Que tan nutritivo es el forraje hidroponico',
    'El forraje hidropónico es un alimento altamente eficaz, excepcionalmente nutritivo , que produce la mayor cantidad de proteínas, energía y es muy rico en vitaminas como el B-caroteno, oligoelementos, hormonas, factores de crecimiento y enzima']

    #  humus de lombris